### PR TITLE
Update go module path declaration

### PR DESCRIPTION
**Pull request by ahmet**
```sh
➜ go get github.com/bybit-exchange/bybit.go.api
go: downloading github.com/bybit-exchange/bybit.go.api v0.0.0-20240222172100-8a4f616e98e4
go: github.com/bybit-exchange/bybit.go.api@upgrade (v0.0.0-20240222172100-8a4f616e98e4) requires github.com/bybit-exchange/bybit.go.api@v0.0.0-20240222172100-8a4f616e98e4: parsing go.mod:
	module declares its path as: github.com/wuhewuhe/bybit.go.api
	        but was required as: github.com/bybit-exchange/bybit.go.api
```

### CODE REVIEW

**Comment by AlexChernov** [comment]
It's not enough, there should be changes in imports as well

**Comment by ahmet** [comment]
hyg ✌🏼

**Comment by mateusfmello** [comment]
Will this PR not be merged?

**Review by mateusfmello — APPROVED** [review]
Full fixes.

**Pull request closed without merging**
